Perso
Triw-12/Trieur-de-jeu pull request #14
Opened 2024-11-15 15:50 UTC by RaptorJesus82

Modifications pour s'adapter à  la structure de stockage des images, création d'une page login et modification de la page signup.

2024-11-15 18:48 UTC, Triw-12 reviewed
Globalement c'est ok, y'a juste quelques détails qui ne sont pas ok

2024-11-15 18:48 UTC, Triw-12 commented on website/authentification/views.py
> +                message = f'Bonjour, {user.username}! Vous êtes connecté.'
```suggestion
                message = f'Bonjour, {user.username}! Vous êtes connecté.'
                return redirect('home')
```

2024-11-15 18:48 UTC, Triw-12 commented on website/authentification/views.py
> +    form = forms.LoginForm()
```suggestion
    form = forms.LoginForm()
    if request.user.is_authenticated:
        return redirect('home')
```
Si l'utilisateur est déjà connecté, on redirige directement vers le home

2024-11-15 18:48 UTC, Triw-12 commented on website/authentification/views.py
> +                message = 'Identifiants invalides.'
Faudra penser à mettre les messages dans le contexte....

2024-11-15 18:48 UTC, Triw-12 commented on website/templates/base.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymo
Il est possible d'intégrer bootstrap directement comme une application : [https://www.w3schools.com/django/django_add_bootstrap5.php](https://www.w3schools.com/django/django_add_bootstrap5.php)

2024-11-15 18:48 UTC, Triw-12 commented on website/website/settings.py
> +ALLOWED_HOSTS = ['*']
Pourquoi tu as changé ça ?

2024-11-19 13:09 UTC, RaptorJesus82 commented on website/website/settings.py
> +ALLOWED_HOSTS = ['*']
Permet de se connecter avec son téléphone au site

2024-11-19 15:40 UTC, Triw-12 requested changes

2024-11-19 15:40 UTC, Triw-12 commented on website/templates/base.html
> +<link rel="stylesheet" href="{% static 'CSS/base.css' %}">
Faut le mettre dans le head...

2024-11-19 16:37 UTC, Triw-12 approved these changes

2024-11-19 16:38 UTC, merged